# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BAD Engineering Github Sandbox Website
email: badengineeringllc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official unnofficial web page for BAD Engineering LLC
baseurl: "/sandbox" # the subpath of your site, e.g. /blog
url: "http://badengineers.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  BADEngineering

# Build settings
markdown: kramdown
