# Site settings
title: Ion
email: badengineeringllc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official unofficial website for BAD Engineering LLC
baseurl: "/sandbox/" # the subpath of your site, e.g. /blog/
url: "http://badengineers.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  BADEngineering

# Build settings
markdown: kramdown
